
// This file has been generated by the GUI designer. Do not modify.
namespace SGM
{
	public partial class CashdeskWindow
	{
		private global::Gtk.Label testLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SGM.CashdeskWindow
			this.Name = "SGM.CashdeskWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("CashdeskWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child SGM.CashdeskWindow.Gtk.Container+ContainerChild
			this.testLabel = new global::Gtk.Label ();
			this.testLabel.Name = "testLabel";
			this.testLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Hey");
			this.Add (this.testLabel);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
