
// This file has been generated by the GUI designer. Do not modify.
namespace SGM
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action SGMAction;
		
		private global::Gtk.Action deleteAction;
		
		private global::Gtk.Action restart;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Button createCustomer;
		
		private global::Gtk.Button createCashdesk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SGM.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.SGMAction = new global::Gtk.Action ("SGMAction", global::Mono.Unix.Catalog.GetString ("SGM"), null, null);
			this.SGMAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Test");
			w1.Add (this.SGMAction, null);
			this.deleteAction = new global::Gtk.Action ("deleteAction", global::Mono.Unix.Catalog.GetString ("Beenden"), null, "gtk-delete");
			this.deleteAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Beenden");
			w1.Add (this.deleteAction, null);
			this.restart = new global::Gtk.Action ("restart", global::Mono.Unix.Catalog.GetString ("Neustarten"), null, "gtk-refresh");
			this.restart.ShortLabel = global::Mono.Unix.Catalog.GetString ("Neustarten");
			w1.Add (this.restart, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "SGM.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("SGM");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child SGM.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.createCustomer = new global::Gtk.Button ();
			this.createCustomer.CanFocus = true;
			this.createCustomer.Name = "createCustomer";
			this.createCustomer.UseUnderline = true;
			this.createCustomer.Label = "Neuen Kunden erstellen";
			this.vbox2.Add (this.createCustomer);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.createCustomer]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.createCashdesk = new global::Gtk.Button ();
			this.createCashdesk.CanFocus = true;
			this.createCashdesk.Name = "createCashdesk";
			this.createCashdesk.UseUnderline = true;
			this.createCashdesk.Label = global::Mono.Unix.Catalog.GetString ("Neue Kasse erstellen");
			this.vbox2.Add (this.createCashdesk);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.createCashdesk]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.hbox2.Add (this.vbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			this.hbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbox2]));
			w5.Position = 0;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w6.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 778;
			this.DefaultHeight = 484;
			this.Show ();
			this.createCustomer.Clicked += new global::System.EventHandler (this.onCreateCustomerClicked);
			this.createCashdesk.Clicked += new global::System.EventHandler (this.onCreateCashdeskClicked);
		}
	}
}
